name: Build & Ship
on:
  pull_request:
  merge_group:
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run Detekt
        uses: eskatos/gradle-command-action@v2
        with:
          arguments: detekt

      - name: Run Unit Tests
        run: ./gradlew test --stacktrace

      - name: Assemble Debug
        uses: eskatos/gradle-command-action@v2
        with:
          arguments: assembleDebug
