name: Build & Ship
on:
  pull_request:
  merge_group:
jobs:
    gradle:
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
        - uses: actions/checkout@v3

        - name: Set Java 11
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: 11

        - name: assembleDebug
          uses: eskatos/gradle-command-action@v2
          with:
            arguments: assembleDebug

        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk
